In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [2]:
irisdata = load_iris()

In [3]:
irisdata.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
x = irisdata.data
print(x.shape)
y = irisdata.target
print(y.shape)

(150, 4)
(150,)


In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.3,random_state=42)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
knn.score(x_test,y_test)

1.0

In [14]:
y_pred = knn.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [22]:
y_test.shape

(45,)

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix
score = accuracy_score(y_test,y_pred)
print('Accuracy of model : ',score)

con_matrix = confusion_matrix(y_test,y_pred)
print('Correct and Incorrect Prediction : ','\n',con_matrix,end=' ')

Accuracy of model :  1.0
Correct and Incorrect Prediction :  
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]] 

In [25]:
#19+13+13 = 45 correct prediction.There is no any wrong prediction